# ytm-tui - a terminal player for your YouTube Music account.
# Copyright (C) 2026 shuka0158
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Cookie authentication for yt-dlp.

Sign-in gated tracks ("Sign in to confirm your age") only play if yt-dlp sends
a logged-in session. We already hold one: `ytm setup` stores the request headers
of a signed-in music.youtube.com call, cookie header included. This module turns
that header into the Netscape cookies.txt yt-dlp wants, so nobody has to export
cookies a second time.

Reading the browser's own cookie store stays available as a fallback for people
who authenticated some other way.
"""
from __future__ import annotations

import json
import os
import shutil
import sqlite3
import tempfile
import time
import webbrowser
from http.cookies import SimpleCookie
from pathlib import Path

from . import config

# Where to send someone who has no session at all.
LOGIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fmusic.youtube.com%2F"

# Cookies in a request header carry no domain or expiry, so we supply both.
# YouTube's session cookies are set on the registrable domain, and a year is
# well past the point where Google would have rotated them anyway.
COOKIE_DOMAIN = ".youtube.com"
COOKIE_TTL = 365 * 24 * 3600

# First-party session cookies. __Secure-3PSID deliberately is not one: browsers
# pick it up from embedded players, so a profile that never signed in has it.
SESSION_COOKIES = ("LOGIN_INFO", "SID", "__Secure-1PSID")

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by ytm-tui from the credentials saved by `ytm setup`.\n"
    "# Treat this file like a password: it is a live Google session.\n"
)


def _auth_cookie_header() -> str | None:
    """The raw Cookie header from the credentials `ytm setup` saved, if any."""
    if not config.BROWSER_AUTH.exists():
        return None
    try:
        data = json.loads(config.BROWSER_AUTH.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    if not isinstance(data, dict):
        return None
    for key, value in data.items():  # header names are case-insensitive
        if key.lower() == "cookie" and isinstance(value, str) and value.strip():
            return value
    return None


def parse_cookie_header(header: str) -> dict[str, str]:
    """name=value pairs from a Cookie request header, bad pairs skipped."""
    jar = SimpleCookie()
    try:
        jar.load(header)
    except Exception:
        # One malformed pair poisons the whole load, so fall back to splitting.
        jar = SimpleCookie()
        for chunk in header.split(";"):
            name, sep, value = chunk.strip().partition("=")
            if sep and name:
                try:
                    jar[name] = value
                except Exception:
                    continue
    return {name: morsel.value for name, morsel in jar.items() if morsel.value}


def to_netscape(cookies: dict[str, str], expiry: int | None = None) -> str:
    """Render name=value pairs as a Netscape cookies.txt body."""
    expires = int(expiry if expiry is not None else time.time() + COOKIE_TTL)
    lines = [NETSCAPE_HEADER]
    for name, value in cookies.items():
        # domain, include-subdomains, path, secure, expiry, name, value
        lines.append(
            "\t".join((COOKIE_DOMAIN, "TRUE", "/", "TRUE", str(expires), name, value))
        )
    return "\n".join(lines) + "\n"


def has_session(cookies: dict[str, str]) -> bool:
    return any(name in cookies for name in SESSION_COOKIES)


def sync_from_auth(force: bool = False) -> Path | None:
    """Regenerate config/cookies.txt from the saved credentials.

    Returns the path when a usable session was written, None otherwise. Cheap
    enough to call on every start: it rewrites only when the credentials changed.
    """
    header = _auth_cookie_header()
    if not header:
        return None

    target = config.COOKIES_FILE
    if not force and target.exists():
        try:
            if target.stat().st_mtime >= config.BROWSER_AUTH.stat().st_mtime:
                return target
        except OSError:
            pass

    cookies = parse_cookie_header(header)
    if not has_session(cookies):
        return None

    config.ensure_dirs()
    try:
        # Written private-first: this is a live session, not a cache file.
        fd = os.open(str(target), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as handle:
            handle.write(to_netscape(cookies))
    except OSError:
        return None
    return target


def resolve_source(settings: dict) -> tuple[str | None, str | None]:
    """Pick the cookie source for this run.

    Returns (cookies_from_browser, cookies_file); both None means anonymous.
    An explicit setting always wins, otherwise we fall back to the session
    `ytm setup` already gave us.
    """
    browser = settings.get("cookies_from_browser")
    if browser:
        return browser, None

    path = settings.get("cookies_file")
    if path:
        return None, str(path)

    generated = sync_from_auth()
    return None, str(generated) if generated else None


# --- browser cookie stores -------------------------------------------------
# Only used when someone explicitly points us at a browser; the generated file
# above is the default path and needs none of this.

def _sqlite_cookie_names(db: Path, table: str, host_column: str) -> set[str]:
    """Cookie names for youtube.com in a browser store, read via a copy.

    Browsers hold a lock on the live database, so never open it in place.
    """
    tmp = Path(tempfile.mkdtemp()) / "cookies"
    try:
        shutil.copy(db, tmp)
        with sqlite3.connect(tmp) as conn:
            rows = conn.execute(
                # Table and column are ours, not user input.
                f"SELECT name FROM {table} WHERE {host_column} LIKE '%youtube.com'"
            ).fetchall()
        return {row[0] for row in rows}
    except (OSError, sqlite3.Error):
        return set()
    finally:
        shutil.rmtree(tmp.parent, ignore_errors=True)


def _profile_spec(browser: str, profile_dir: Path, root: Path) -> str:
    """The `--cookies-from-browser` string for one profile directory."""
    if profile_dir == root or profile_dir.name in ("Default", "default"):
        return browser
    # Chromium takes a profile name, Firefox needs the full profile path.
    name = profile_dir.name if browser != "firefox" else str(profile_dir)
    return f"{browser}:{name}"


def detect_browsers() -> list[str]:
    """`--cookies-from-browser` specs whose profile is signed in to YouTube.

    Best-effort and read-only: a profile we cannot read is simply not offered.
    """
    home = Path.home()
    found: list[str] = []

    chromium_roots = {
        "chrome": home / ".config/google-chrome",
        "chromium": home / ".config/chromium",
        "brave": home / ".config/BraveSoftware/Brave-Browser",
        "edge": home / ".config/microsoft-edge",
        "vivaldi": home / ".config/vivaldi",
        "opera": home / ".config/opera",
    }
    for browser, root in chromium_roots.items():
        if not root.is_dir():
            continue
        for db in sorted(root.glob("*/Cookies")) + sorted(root.glob("*/Network/Cookies")):
            profile = db.parent if db.parent.name != "Network" else db.parent.parent
            names = _sqlite_cookie_names(db, "cookies", "host_key")
            if has_session({n: "x" for n in names}):
                found.append(_profile_spec(browser, profile, root))

    firefox_root = home / ".mozilla/firefox"
    if firefox_root.is_dir():
        for db in sorted(firefox_root.glob("*/cookies.sqlite")):
            names = _sqlite_cookie_names(db, "moz_cookies", "host")
            if has_session({n: "x" for n in names}):
                found.append(_profile_spec("firefox", db.parent, firefox_root))

    # Same profile can show up twice via both Cookies paths; keep first sighting.
    return list(dict.fromkeys(found))


def open_login_page() -> bool:
    """Open the YouTube sign-in page in the default browser. Never raises."""
    try:
        return webbrowser.open(LOGIN_URL, new=2)
    except Exception:
        return False
